// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4HZTzEqdDeAzIyQmMBV7i5g2250ZR8LA',
    appId: '1:955555494507:web:0ce3096537f059f6efcf2e',
    messagingSenderId: '955555494507',
    projectId: 'khidmat-29d2a',
    authDomain: 'khidmat-29d2a.firebaseapp.com',
    storageBucket: 'khidmat-29d2a.firebasestorage.app',
    measurementId: 'G-BRTYKXWCD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3nRsAvpy7fICR3rKw8b_6eGBc8ufyhM',
    appId: '1:955555494507:android:8b7448569716a9aaefcf2e',
    messagingSenderId: '955555494507',
    projectId: 'khidmat-29d2a',
    storageBucket: 'khidmat-29d2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2afC9wPCltRdFNv_Bi2ZMFRmNboPS0w',
    appId: '1:955555494507:ios:45a74c9e1872d1efefcf2e',
    messagingSenderId: '955555494507',
    projectId: 'khidmat-29d2a',
    storageBucket: 'khidmat-29d2a.firebasestorage.app',
    iosBundleId: 'com.example.khidmat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2afC9wPCltRdFNv_Bi2ZMFRmNboPS0w',
    appId: '1:955555494507:ios:45a74c9e1872d1efefcf2e',
    messagingSenderId: '955555494507',
    projectId: 'khidmat-29d2a',
    storageBucket: 'khidmat-29d2a.firebasestorage.app',
    iosBundleId: 'com.example.khidmat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4HZTzEqdDeAzIyQmMBV7i5g2250ZR8LA',
    appId: '1:955555494507:web:e4f04a9818ec91ccefcf2e',
    messagingSenderId: '955555494507',
    projectId: 'khidmat-29d2a',
    authDomain: 'khidmat-29d2a.firebaseapp.com',
    storageBucket: 'khidmat-29d2a.firebasestorage.app',
    measurementId: 'G-806QYYS3B5',
  );
}
